version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
        - checkout
        # Maybe you need to add some config file specific to circle…
        #- run: cp .circleci/.some-parameter-file .some-parameter-file
        - run: docker-compose up -d
        - store_artifacts:
            path: ~/repo/features/fail-screenshots
        - ghostinspector/test-docker-app:
            api-key: $GHOST_API_KEY
            suite-id: $GHOST_SUITE_ID
            vpn-token: $NGROK_TOKEN
            vpn-target: 'my-docker-image:80'